"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { createSupabaseBrowser } from "@/lib/supabase/client";
import { useProfile } from "@/lib/useProfile";

type Branding = {
  tenant_id: string;
  company_name: string | null;
  header_text: string | null;
  footer_text: string | null;
  logo_path: string | null;
  accent_hex: string | null;
};

export default function ExportsPage() {
  const supabase = createSupabaseBrowser();
  const { reportId } = useParams<{ reportId: string }>();
  const { loading: pLoading, profile } = useProfile();

  const [branding, setBranding] = useState<Branding | null>(null);
  const [saving, setSaving] = useState(false);
  const [msg, setMsg] = useState<string | null>(null);

  // fields
  const [companyName, setCompanyName] = useState("Valeron");
  const [headerText, setHeaderText] = useState("Valeron • Reportz Demo");
  const [footerText, setFooterText] = useState("Generated by Reportz");
  const [accentHex, setAccentHex] = useState("#dd622d");
  const [logoFile, setLogoFile] = useState<File | null>(null);

  useEffect(() => {
    async function loadBranding() {
      if (!profile?.tenant_id) return;

      const { data, error } = await supabase
        .from("tenant_branding")
        .select("tenant_id, company_name, header_text, footer_text, logo_path, accent_hex")
        .eq("tenant_id", profile.tenant_id)
        .maybeSingle();

      if (!error && data) {
        setBranding(data as Branding);
        setCompanyName(data.company_name ?? "Valeron");
        setHeaderText(data.header_text ?? "Valeron • Reportz Demo");
        setFooterText(data.footer_text ?? "Generated by Reportz");
        setAccentHex(data.accent_hex ?? "#dd622d");
      }
    }

    if (!pLoading) loadBranding();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [pLoading, profile?.tenant_id]);

  async function saveBranding() {
    if (!profile?.tenant_id) return;

    setSaving(true);
    setMsg(null);

    let logo_path = branding?.logo_path ?? null;

    // 1) Upload logo if provided
    if (logoFile) {
      const ext = (logoFile.name.split(".").pop() || "png").toLowerCase();
      const path = `${profile.tenant_id}/logo.${ext}`;

      const { error: upErr } = await supabase.storage
        .from("branding-logos")
        .upload(path, logoFile, { upsert: true, cacheControl: "3600" });

      if (upErr) {
        setSaving(false);
        setMsg(`Logo upload failed: ${upErr.message}`);
        return;
      }
      logo_path = path;
    }

    // 2) Upsert branding row
    const { error } = await supabase.from("tenant_branding").upsert(
      {
        tenant_id: profile.tenant_id,
        company_name: companyName,
        header_text: headerText,
        footer_text: footerText,
        accent_hex: accentHex,
        logo_path,
        updated_at: new Date().toISOString(),
      },
      { onConflict: "tenant_id" }
    );

    setSaving(false);

    if (error) {
      setMsg(`Save failed: ${error.message}`);
    } else {
      setMsg("✅ Branding saved");
      setBranding({
        tenant_id: profile.tenant_id,
        company_name: companyName,
        header_text: headerText,
        footer_text: footerText,
        accent_hex: accentHex,
        logo_path,
      });
      setLogoFile(null);
    }
  }

  function exportWord() {
    window.open(`/api/export-report?reportId=${reportId}`, "_blank");
  }

  if (pLoading) return <p>Loading…</p>;
  if (!profile?.tenant_id) return <p>Tenant not set on your profile.</p>;

  return (
    <div style={{ maxWidth: 900 }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <h1 style={{ margin: 0 }}>Exports</h1>
        <div style={{ display: "flex", gap: 12 }}>
          <Link href={`/reports/${reportId}`}>Report</Link>
          <Link href={`/reports/${reportId}/work-orders`}>Work Orders</Link>
        </div>
      </div>

      <div style={{ marginTop: 16, padding: 12, border: "1px solid #333", borderRadius: 10 }}>
        <h2 style={{ marginTop: 0 }}>Branding (per client/tenant)</h2>

        <div style={{ display: "grid", gap: 10 }}>
          <label>
            <div style={{ fontSize: 12, opacity: 0.8 }}>Company name</div>
            <input
              value={companyName}
              onChange={(e) => setCompanyName(e.target.value)}
              style={{ width: "100%", padding: 10 }}
            />
          </label>

          <label>
            <div style={{ fontSize: 12, opacity: 0.8 }}>Header text</div>
            <input
              value={headerText}
              onChange={(e) => setHeaderText(e.target.value)}
              style={{ width: "100%", padding: 10 }}
            />
          </label>

          <label>
            <div style={{ fontSize: 12, opacity: 0.8 }}>Footer text</div>
            <input
              value={footerText}
              onChange={(e) => setFooterText(e.target.value)}
              style={{ width: "100%", padding: 10 }}
            />
          </label>

          <label>
            <div style={{ fontSize: 12, opacity: 0.8 }}>Accent colour (hex)</div>
            <input
              value={accentHex}
              onChange={(e) => setAccentHex(e.target.value)}
              style={{ width: 220, padding: 10 }}
            />
          </label>

          <label>
            <div style={{ fontSize: 12, opacity: 0.8 }}>Logo (PNG recommended)</div>
            <input
              type="file"
              accept="image/*"
              onChange={(e) => setLogoFile(e.target.files?.[0] ?? null)}
            />
          </label>

          <div style={{ display: "flex", gap: 12, alignItems: "center" }}>
            <button onClick={saveBranding} disabled={saving}>
              {saving ? "Saving…" : "Save branding"}
            </button>
            {msg ? <span>{msg}</span> : null}
          </div>
        </div>
      </div>

      <div style={{ marginTop: 16, display: "flex", gap: 12 }}>
        <button onClick={exportWord} style={{ padding: "10px 12px", fontWeight: 800 }}>
          Export Word (.docx)
        </button>
      </div>
    </div>
  );
}
