"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { createSupabaseBrowser } from "@/lib/supabase/client";
import { useProfile } from "@/lib/useProfile";

type Branding = {
  tenant_id: string;
  company_name: string | null;
  header_text: string | null;
  footer_text: string | null;
  logo_path: string | null;
  accent_hex: string | null;
};

export default function ExportsPage() {
  const supabase = createSupabaseBrowser();
  const { reportId } = useParams<{ reportId: string }>();
  const { loading: pLoading, profile } = useProfile();

  const [branding, setBranding] = useState<Branding | null>(null);
  const [saving, setSaving] = useState(false);
  const [msg, setMsg] = useState<string | null>(null);

  const [companyName, setCompanyName] = useState("Valeron");
  const [headerText, setHeaderText] = useState("Valeron | Reportz Demo");
  const [footerText, setFooterText] = useState("Generated by Reportz");
  const [accentHex, setAccentHex] = useState("#dd622d");
  const [logoFile, setLogoFile] = useState<File | null>(null);

  useEffect(() => {
    async function loadBranding() {
      if (!profile?.tenant_id) return;

      const { data, error } = await supabase
        .from("tenant_branding")
        .select("tenant_id, company_name, header_text, footer_text, logo_path, accent_hex")
        .eq("tenant_id", profile.tenant_id)
        .maybeSingle();

      if (!error && data) {
        setBranding(data as Branding);
        setCompanyName(data.company_name ?? "Valeron");
        setHeaderText(data.header_text ?? "Valeron | Reportz Demo");
        setFooterText(data.footer_text ?? "Generated by Reportz");
        setAccentHex(data.accent_hex ?? "#dd622d");
      }
    }

    if (!pLoading) loadBranding();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [pLoading, profile?.tenant_id]);

  async function saveBranding() {
    if (!profile?.tenant_id) return;

    setSaving(true);
    setMsg(null);

    let logo_path = branding?.logo_path ?? null;

    if (logoFile) {
      const ext = (logoFile.name.split(".").pop() || "png").toLowerCase();
      const path = `${profile.tenant_id}/logo.${ext}`;

      const { error: upErr } = await supabase.storage
        .from("branding-logos")
        .upload(path, logoFile, { upsert: true, cacheControl: "3600" });

      if (upErr) {
        setSaving(false);
        setMsg(`Logo upload failed: ${upErr.message}`);
        return;
      }
      logo_path = path;
    }

    const { error } = await supabase.from("tenant_branding").upsert(
      {
        tenant_id: profile.tenant_id,
        company_name: companyName,
        header_text: headerText,
        footer_text: footerText,
        accent_hex: accentHex,
        logo_path,
        updated_at: new Date().toISOString(),
      },
      { onConflict: "tenant_id" }
    );

    setSaving(false);

    if (error) {
      setMsg(`Save failed: ${error.message}`);
    } else {
      setMsg("Branding saved");
      setBranding({
        tenant_id: profile.tenant_id,
        company_name: companyName,
        header_text: headerText,
        footer_text: footerText,
        accent_hex: accentHex,
        logo_path,
      });
      setLogoFile(null);
    }
  }

  function exportWord() {
    window.open(`/api/export-report?reportId=${reportId}`, "_blank");
  }

  if (pLoading) return <p className="muted">Loading...</p>;
  if (!profile?.tenant_id) return <p className="muted">Tenant not set on your profile.</p>;

  return (
    <div className="grid" style={{ maxWidth: 960 }}>
      <div className="title-row">
        <h1>Exports</h1>
        <div style={{ display: "flex", gap: "0.55rem", flexWrap: "wrap" }}>
          <Link className="btn btn-soft" href={`/reports/${reportId}`}>
            Report
          </Link>
          <Link className="btn btn-soft" href={`/reports/${reportId}/work-orders`}>
            Work Orders
          </Link>
        </div>
      </div>

      <div className="section-card grid">
        <h2 style={{ marginBottom: "0.3rem" }}>Branding</h2>

        <label className="field">
          <span className="label">Company name</span>
          <input className="input" value={companyName} onChange={(e) => setCompanyName(e.target.value)} />
        </label>

        <label className="field">
          <span className="label">Header text</span>
          <input className="input" value={headerText} onChange={(e) => setHeaderText(e.target.value)} />
        </label>

        <label className="field">
          <span className="label">Footer text</span>
          <input className="input" value={footerText} onChange={(e) => setFooterText(e.target.value)} />
        </label>

        <label className="field" style={{ maxWidth: 260 }}>
          <span className="label">Accent color (hex)</span>
          <input className="input" value={accentHex} onChange={(e) => setAccentHex(e.target.value)} />
        </label>

        <label className="field">
          <span className="label">Logo (PNG recommended)</span>
          <div style={{ display: "flex", gap: "0.6rem", alignItems: "center", flexWrap: "wrap" }}>
            <label className="btn btn-soft" style={{ cursor: "pointer", width: "fit-content" }}>
              Choose logo
              <input
                type="file"
                accept="image/*"
                style={{ display: "none" }}
                onChange={(e) => setLogoFile(e.target.files?.[0] ?? null)}
              />
            </label>
            {logoFile ? <span className="muted">{logoFile.name}</span> : <span className="muted">No file selected</span>}
          </div>
        </label>

        <div style={{ display: "flex", gap: "0.6rem", alignItems: "center", flexWrap: "wrap" }}>
          <button className="btn btn-primary" onClick={saveBranding} disabled={saving}>
            {saving ? "Saving..." : "Save branding"}
          </button>
          {msg ? <span className={msg.toLowerCase().includes("failed") ? "error-text" : "muted"}>{msg}</span> : null}
        </div>
      </div>

      <div>
        <button className="btn" onClick={exportWord}>
          Export PowerPoint (.pptx)
        </button>
      </div>
    </div>
  );
}

