export const runtime = "nodejs";

import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import {
  AlignmentType,
  BorderStyle,
  Document,
  Footer,
  Header,
  HeadingLevel,
  ImageRun,
  Packer,
  PageBreak,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from "docx";

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

type BrandingRow = {
  tenant_id: string;
  company_name: string | null;
  header_text: string | null;
  footer_text: string | null;
  logo_path: string | null;
  accent_hex: string | null;
};

function safeFileName(name: string) {
  return name
    .replace(/[<>:"/\\|?*\x00-\x1F]/g, "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 80);
}

function noBorders() {
  return {
    top: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
    bottom: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
    left: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
    right: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
    insideHorizontal: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
    insideVertical: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
  };
}

function dashboardRow(label: string, value: string) {
  return new TableRow({
    children: [
      new TableCell({
        children: [
          new Paragraph({
            children: [new TextRun({ text: label, bold: true })],
          }),
        ],
      }),
      new TableCell({
        children: [new Paragraph(value)],
      }),
    ],
  });
}

async function downloadStorageFile(bucket: string, path: string): Promise<Buffer | null> {
  const { data, error } = await supabase.storage.from(bucket).download(path);
  if (error || !data) return null;
  const ab = await data.arrayBuffer();
  return Buffer.from(ab);
}

function guessImageType(pathOrName: string): "png" | "jpg" {
  const lower = (pathOrName || "").toLowerCase();
  if (lower.endsWith(".png")) return "png";
  return "jpg";
}

export async function GET(req: NextRequest) {
  try {
    const reportId = req.nextUrl.searchParams.get("reportId");
    if (!reportId) {
      return NextResponse.json({ error: "Missing reportId" }, { status: 400 });
    }

    // =========================
    // FETCH REPORT
    // =========================
    const { data: report, error: repErr } = await supabase
      .from("reports")
      .select("id, name, start_date, end_date, tenant_id")
      .eq("id", reportId)
      .single();

    if (repErr || !report) {
      return NextResponse.json({ error: repErr?.message || "Report not found" }, { status: 404 });
    }

    // =========================
    // BRANDING (tenant)
    // =========================
    let branding: BrandingRow | null = null;
    let logoBuf: Buffer | null = null;
    const tenantId = (report as any).tenant_id as string | undefined;

    if (tenantId) {
      const { data: b } = await supabase
        .from("tenant_branding")
        .select("tenant_id, company_name, header_text, footer_text, logo_path, accent_hex")
        .eq("tenant_id", tenantId)
        .maybeSingle();

      branding = (b as BrandingRow) ?? null;

      if (branding?.logo_path) {
        logoBuf = await downloadStorageFile("branding-logos", branding.logo_path);
      }
    }

    const companyName = branding?.company_name || "Valeron";
    const headerText = branding?.header_text || "Valeron • Reportz Demo";
    const footerText = branding?.footer_text || "Generated by Reportz";
    const logoType = branding?.logo_path ? guessImageType(branding.logo_path) : "png";

    // =========================
    // WORK ORDERS
    // =========================
    const { data: workOrders, error: woErr } = await supabase
      .from("work_orders")
      .select("id, report_id, wo_number, title, status, cancelled_reason, completed_at")
      .eq("report_id", reportId)
      .order("wo_number", { ascending: true });

    if (woErr) return NextResponse.json({ error: woErr.message }, { status: 500 });

    const wos = workOrders ?? [];
    const woIds = wos.map((w) => w.id);

    // =========================
    // UPDATES (comments + photo paths)
    // =========================
    const { data: updates, error: updErr } = await supabase
      .from("wo_updates")
      .select("id, work_order_id, comment, photo_urls, created_at")
      .in("work_order_id", woIds.length ? woIds : ["00000000-0000-0000-0000-000000000000"])
      .order("created_at", { ascending: true });

    if (updErr) return NextResponse.json({ error: updErr.message }, { status: 500 });

    const updatesByWo = new Map<string, any[]>();
    for (const u of updates ?? []) {
      const key = u.work_order_id as string;
      if (!updatesByWo.has(key)) updatesByWo.set(key, []);
      updatesByWo.get(key)!.push(u);
    }

    // =========================
    // DASHBOARD METRICS
    // =========================
    const total = wos.length;
    const complete = wos.filter((w) => w.status === "complete").length;
    const cancelled = wos.filter((w) => w.status === "cancelled").length;
    const open = total - complete - cancelled;

    // =========================
    // HEADER (borderless)
    // =========================
    const header = new Header({
      children: [
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          layout: "fixed",
          borders: noBorders(),
          rows: [
            // Row 1: logo left, header text right
            new TableRow({
              children: [
                new TableCell({
                  width: { size: 30, type: WidthType.PERCENTAGE },
                  margins: { top: 80, bottom: 0, left: 0, right: 0 },
                  borders: noBorders(),
                  children: [
                    new Paragraph({
                      children: logoBuf
                        ? [
                            new ImageRun({
                              data: logoBuf,
                              transformation: { width: 110, height: 40 },
                              type: logoType,
                            }),
                          ]
                        : [],
                    }),
                  ],
                }),
                new TableCell({
                  width: { size: 70, type: WidthType.PERCENTAGE },
                  margins: { top: 80, bottom: 0, left: 0, right: 0 },
                  borders: noBorders(),
                  children: [
                    new Paragraph({
                      alignment: AlignmentType.RIGHT,
                      children: [new TextRun({ text: headerText, bold: true, size: 20 })],
                    }),
                  ],
                }),
              ],
            }),

            // Row 2: centred details (one cell spanning both columns)
            new TableRow({
              children: [
                new TableCell({
                  columnSpan: 2,
                  borders: noBorders(),
                  margins: { top: 40, bottom: 120, left: 0, right: 0 },
                  children: [
                    new Paragraph({
                      alignment: AlignmentType.CENTER,
                      children: [
                        new TextRun({
                          text: `${companyName}  |  ${report.name ?? "Shutdown"}  |  ${
                            report.start_date ?? "?"
                          } → ${report.end_date ?? "?"}`,
                          size: 18,
                        }),
                      ],
                    }),
                  ],
                }),
              ],
            }),
          ],
        }),
      ],
    });

    // =========================
    // FOOTER
    // =========================
    const footer = new Footer({
      children: [
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: footerText, size: 20 })],
        }),
      ],
    });

    // =========================
    // TITLE PAGE
    // =========================
    const titlePage = [
      new Paragraph({
        text: companyName,
        heading: HeadingLevel.HEADING_1,
        alignment: AlignmentType.CENTER,
        spacing: { after: 250 },
      }),
      new Paragraph({
        text: "Shutdown Report",
        heading: HeadingLevel.TITLE,
        alignment: AlignmentType.CENTER,
        spacing: { after: 450 },
      }),
      new Paragraph({
        text: report.name ?? "Untitled Shutdown",
        heading: HeadingLevel.HEADING_1,
        alignment: AlignmentType.CENTER,
        spacing: { after: 250 },
      }),
      new Paragraph({
        text: `Dates: ${report.start_date ?? "?"} → ${report.end_date ?? "?"}`,
        alignment: AlignmentType.CENTER,
        spacing: { after: 350 },
      }),
      new Paragraph({
        text: `Generated: ${new Date().toLocaleString()}`,
        alignment: AlignmentType.CENTER,
        spacing: { after: 200 },
      }),
      new Paragraph({ children: [new PageBreak()] }),
    ];

    // =========================
    // DASHBOARD PAGE
    // =========================
    const dashboardTable = new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: [
        dashboardRow("Total Work Orders", String(total)),
        dashboardRow("Completed", String(complete)),
        dashboardRow("Open", String(open)),
        dashboardRow("Cancelled", String(cancelled)),
      ],
    });

    const dashboardPage = [
      new Paragraph({
        text: "Dashboard Summary",
        heading: HeadingLevel.HEADING_1,
        spacing: { after: 280 },
      }),
      dashboardTable,
      new Paragraph({ children: [new PageBreak()] }),
    ];

    // =========================
    // WORK ORDERS (updates + photos)
    // =========================
    const woContent: Paragraph[] = [
      new Paragraph({
        text: "Work Orders",
        heading: HeadingLevel.HEADING_1,
        spacing: { after: 240 },
      }),
    ];

    for (const w of wos) {
      woContent.push(
        new Paragraph({
          text: `${w.wo_number} — ${w.title || ""}`.trim(),
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 220, after: 60 },
        }),
        new Paragraph({
          children: [
            new TextRun({ text: `Status: ${w.status}` }),
            ...(w.status === "cancelled" && w.cancelled_reason
              ? [new TextRun({ text: `  •  Reason: ${w.cancelled_reason}` })]
              : []),
          ],
          spacing: { after: 140 },
        })
      );

      const woUpdates = updatesByWo.get(w.id) ?? [];
      if (woUpdates.length === 0) {
        woContent.push(new Paragraph({ text: "No updates recorded.", spacing: { after: 220 } }));
        woContent.push(new Paragraph({ children: [new PageBreak()] }));
        continue;
      }

      for (const u of woUpdates) {
        const dt = u.created_at ? new Date(u.created_at).toLocaleString() : "";

        woContent.push(
          new Paragraph({
            children: [new TextRun({ text: dt, italics: true, size: 18 })],
            spacing: { after: 50 },
          })
        );

        if (u.comment) {
          woContent.push(new Paragraph({ text: String(u.comment), spacing: { after: 110 } }));
        }

        const photoPaths: string[] = Array.isArray(u.photo_urls) ? u.photo_urls : [];
        for (const path of photoPaths) {
          const buf = await downloadStorageFile("report-photos", path);
          if (!buf) {
            woContent.push(
              new Paragraph({
                text: `[Photo could not be downloaded: ${path}]`,
                spacing: { after: 110 },
              })
            );
            continue;
          }

          woContent.push(
            new Paragraph({
              children: [
                new ImageRun({
                  data: buf,
                  transformation: { width: 520, height: 320 },
                  type: guessImageType(path),
                }),
              ],
              spacing: { after: 150 },
            })
          );
        }

        woContent.push(new Paragraph({ children: [new TextRun({ text: " " })], spacing: { after: 80 } }));
      }

      woContent.push(new Paragraph({ children: [new PageBreak()] }));
    }

    // =========================
    // BUILD DOC
    // =========================
    const doc = new Document({
      sections: [
        {
          properties: {},
          headers: { default: header },
          footers: { default: footer },
          children: [...titlePage, ...dashboardPage, ...woContent],
        },
      ],
    });

    const buffer = await Packer.toBuffer(doc);
    const fileName = safeFileName(`Report - ${report.name || "Shutdown"}`) || "Report";

    return new NextResponse(buffer, {
      headers: {
        "Content-Type":
          "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "Content-Disposition": `attachment; filename="${fileName}.docx"`,
      },
    });
  } catch (e: any) {
    console.error(e);
    return NextResponse.json({ error: e?.message || "Export failed" }, { status: 500 });
  }
}
